### ISSUE TITLE
No blobs sent to server

### ISSUE THREAD

**Issue by tomatopuree** [elsehow/chunky-webcam#2]
Hi.

This is a really cool project. I was trying to run the example, and there was a problem that I traced to this event:

onRecordingStopped

Specifically, this event is not called with the specified duration (left at the default 1000ms). 

Therefore the callback to send is never called, and no blob is sent to the server.

To reproduce the problem, you would have to 
- clone the repo
- install recordrtc and socket.io-client with npm install --save in /chunky_webcam directory
- npm install in /examples directory
- run npm run watch in /examples directory
- run npm start in /examples directory

**Comment by elsehow** [comment]
@tomatopuree i'm glad you find this package useful!  I'm not really maintaining it any more, but I'll gladly accept a PR that fixes this issue.
